vich_uploader:
    db_driver: orm

    

    mappings:
        receipt_image:
           uri_prefix: /img/receipt
           upload_destination: '%kernel.project_dir%/public/img/receipt'
           #namer: Vich\UploaderBundle\Naming\SmartUniqueNamer