#index:
   # path: /login
   # controller: App\Controller\SecurityController::login
# config/routes.yaml

login:
    path:       /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST


